/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'Inter', 'system-ui', 'sans-serif'],
        'admin': ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        /* Admin Panel — Dark SaaS Theme */
        'admin-bg': '#0d1117',
        'admin-surface': '#161b22',
        'admin-card': '#21262d',
        'admin-border': '#30363d',
        'admin-text': '#e6edf3',
        'admin-muted': '#8b949e',
        'admin-accent': '#58a6ff',
        'admin-purple': '#a371f7',
        'admin-purple-glow': 'rgba(163, 113, 247, 0.15)',
        'admin-blue': '#1f6feb',
        'admin-success': '#3fb950',
        'admin-warning': '#d29922',
        'admin-danger': '#f85149',
        /* App utilisateur — variables CSS (clair / sombre dans index.css) */
        'app-bg': 'rgb(var(--color-app-bg) / <alpha-value>)',
        'app-surface': 'rgb(var(--color-app-surface) / <alpha-value>)',
        'app-card': 'rgb(var(--color-app-card) / <alpha-value>)',
        'app-border': 'rgb(var(--color-app-border) / <alpha-value>)',
        'app-text': 'rgb(var(--color-app-text) / <alpha-value>)',
        'app-muted': 'rgb(var(--color-app-muted) / <alpha-value>)',
        'app-purple': 'rgb(var(--color-app-purple) / <alpha-value>)',
        'app-blue': 'rgb(var(--color-app-blue) / <alpha-value>)',
        'app-success': 'rgb(var(--color-app-success) / <alpha-value>)',
        'app-warning': 'rgb(var(--color-app-warning) / <alpha-value>)',
        'app-danger': 'rgb(var(--color-app-danger) / <alpha-value>)',
        /* Charte bleu/blanc — moderne */
        'chat-bg': '#ffffff',
        'chat-surface': '#f8fafc',
        'chat-primary': '#2563eb',
        'chat-accent': '#0ea5e9',
        'chat-offwhite': '#1e293b',
        'chat-muted': '#64748b',
        'chat-danger': '#ef4444',
        'chat-success': '#22c55e',
        'chat-border': '#e2e8f0',
        /* Compatibilité */
        'corum-blue': '#2563eb',
        'corum-night': '#f1f5f9',
        'corum-turquoise': '#0ea5e9',
        'corum-offwhite': '#1e293b',
        'corum-gray': '#64748b',
        'corum-red': '#ef4444',
        'bg-main': '#ffffff',
        'bg-card': '#ffffff',
        primary: '#2563eb',
        accent: '#0ea5e9',
        danger: '#ef4444',
        success: '#22c55e',
        'text-main': '#1e293b',
        muted: '#64748b',
        /* Style Facebook */
        'fb-bg': '#f0f2f5',
        'fb-card': '#ffffff',
        'fb-blue': '#1877f2',
        'fb-blue-hover': '#166fe5',
        'fb-text': '#050505',
        'fb-text-secondary': '#65676b',
        'fb-border': '#e4e6eb',
        'fb-input-bg': '#f0f2f5',
      },
      spacing: {
        4.5: '18px',
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.2' }],
        h2: ['24px', { lineHeight: '1.3' }],
        h3: ['18px', { lineHeight: '1.4' }],
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(37, 99, 235, 0.1), 0 4px 6px -4px rgba(37, 99, 235, 0.1)',
        'primary': '0 4px 14px 0 rgba(37, 99, 235, 0.25)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.37)',
        'admin-glow': '0 0 20px rgba(163, 113, 247, 0.2)',
        'admin-card': '0 1px 3px rgba(0, 0, 0, 0.3)',
        'app-glow': '0 0 24px rgba(163, 113, 247, 0.25)',
      },
      backdropBlur: {
        'admin': '12px',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '300ms',
        slow: '600ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(.4,0,.2,1)',
      },
    },
  },
  plugins: [],
};
